### ISSUE TITLE
aws-ebs-csi-driver Error: ImagePullBackOff on the windows nodes

### ISSUE THREAD

**Issue by poojaac** [kubernetes-sigs/aws-ebs-csi-driver#1397] opened 2022-09-22 14:02 UTC
/kind bug

We have enabled aws-ebs-csi-driver through helm chart and since we have mixture of linux and windows nodes in our cluster, `enableWindows` value is set to true. But the daemonset is failing to run on the windows nodes and when describing the pod, we got to know that image itself is failed to pull on the windows node. 

**Error - image operating system "linux" cannot be used on this platform**

Kindly assist how we can solve this issue

**Environment**
- Kubernetes version (use `kubectl version`): 1.22
- Driver version: v1.11.3
- Helm chart version: 2.11.0

**Comment by ConnorJC3** [comment] 2022-09-22 14:20
@poojaac Hello, thank you for reporting this issue! I am not able to reproduce this issue, can you provide more information about your kubernetes setup, and perhaps a set of minimal reproduction steps if possible?

Our images use a manifest list, which will cause the container engine (docker/containerd/etc) to automatically pick the appropriate image for the local environment. We currently support Windows versions 1809, 2021 LTSC, and 20H2, and test against the official Windows AMIs that are used by EKS.

**Comment by poojaac** [comment] 2022-09-22 14:38
We have security restrictions which blocks us from pulling the open source images in the EKS cluster. So we first pull the image into the ECR and then use it.

We are pulling the image **k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.11.3** and using the same in the values.yaml.

Please confirm if this image is correct for both linux and windows

**Comment by ConnorJC3** [comment] 2022-09-22 14:47
@poojaac that is the correct image (alternatively, you can use `public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.11.3`), but some tools will not correctly replicate mutli-arch images. `docker pull` followed by `docker push` has this limitation where it will only push and pull images of the OS docker is running on.

You can check whether or not your image was correctly mirrored by running `docker manifest inspect YOUR_REPOSITORY/YOUR_IMAGE:v1.11.3`. It should provide an output similar to @torredil's comment above that includes both `"os": "linux"` and `"os": "windows"`.

If you need a recommendation on a tool that does correctly deal with multi-arch images, I use and recommend [crane](https://github.com/google/go-containerregistry/tree/main/cmd/crane). The relevant command would look like `crane copy k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.11.3 YOUR_REPOSITORY/YOUR_IMAGE:v1.11.3`, which should copy over both the linux and windows part of the image.

**Comment by poojaac** [comment] 2022-09-22 15:04
When inspected the pulled docker image. Below is the output
{
        "schemaVersion": 2,
        "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
        "config": {
                "mediaType": "application/vnd.docker.container.image.v1+json",
                "size": 2169,
                "digest": "sha256:dc876a9bf689987d16d71ed5d45c956d331c9461504add786f5699ba1eb776e7"
        },
        "layers": [
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 1742645,
                        "digest": "sha256:c9a5b97c2853cff850c4909607f94acb9be4ce12ba0ed7791faf5c6b2ffaddbb"
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "digest": "sha256:4b3840ba3ffe9d2bbeeedba8d7f80a018707b048ac02192014f61e7f894fab32"
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 4563243,
                        "digest": "sha256:92e519cd3b8b32a4e524daa384fd1d844a659962e94276606680e773ee4b08b6"
                },
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 12590498,
                        "digest": "sha256:8b7d3c158d3299873edd97c838303914ccb4b439e0145dcac976e7cefcd57904"
                }
        ]

**Comment by ConnorJC3** [comment] 2022-09-22 15:09
That is a linux-only image, as `docker pull` will only pull the image that matches your local OS and cannot be used to mirror multi-arch images like ours. You will need to use a tool that supports such images like `crane` (see my previous comment).

**Comment by poojaac** [comment] 2022-09-22 15:13
@ConnorJC3 Sure, will consider this. Thanks for the hint

**Comment by KlwntSingh** [comment] 2022-09-29 00:32
@ConnorJC3 Please can you please confirm there is no support for windows Server 2022 at this point?

**Comment by ConnorJC3** [comment] 2022-10-03 14:41
@KlwntSingh not as of right now, but see PR #1408 where we're adding support

**Comment by torredil** [comment] 2022-10-10 20:19
Resolving this issue, if help/clarification is still needed feel free to re-open, thanks.

**Closed by torredil** 2022-10-10 20:19 UTC
Labels: kind/bug
