### ISSUE TITLE
EKS EBS Multi attach

### ISSUE THREAD

**Issue by yrsurya** [kubernetes-sigs/aws-ebs-csi-driver#1028] opened 2021-08-18 23:01 UTC
Like to know if this csi driver supports multi attaching ebs volumes that AWS released recently - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volumes-multi.html

use case , we had use case where stateless application downloads video files ( approx 100 GB or more ) to eks pods where it storing in ebs volume that attached to nodes .

we are looking to utilizing ebs csi driver to dynamically provisioned separate ebs volumes but we may have more than 2 replicas where it may spin up in different nodes so like ti know if we can attach that ebs to multiple nodes so more pods can access ebs

Please let me know if need more information

**Comment by voroninman** [comment] 2021-09-01 15:48
A duplicate of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/449.

**Closed** 2022-01-29 17:17 UTC
Labels: lifecycle/rotten

**Comment by FernandoMiguel** [comment] 2023-09-20 08:54
Given how slow sometimes csi is to free up a disk and reattach to a new instance, I too wondered of using multi attach instead.
And would like to know if it is supported by ebs csi driver

**Comment by AndrewSirenko** [comment] 2023-11-16 03:38
FYI this feature was released as a part of [v1.25.0](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md#notable-changes) of our driver!
