### ISSUE TITLE
Resize Volume fails if capacity is modified in PVC for volume of type io1

### ISSUE THREAD

**Issue by jahantech** [kubernetes-sigs/aws-ebs-csi-driver#622] opened 2020-11-25 16:18 UTC
/kind bug

**What happened?**
Resized the volume by modifying the capacity in the PVC resource. However the resize failed with following error:
```
Warning  VolumeResizeFailed  26s  volume_expand  error expanding volume "default/test-pod" of plugin "kubernetes.io/aws-ebs": AWS modifyVolume failed for vol-03a0dcd92e5535e4f with InvalidParameterCombination: The parameter iops must be specified for io1 volumes.
```

**What you expected to happen?**
Successful resizing of the volume should have occurred.

**How to reproduce it (as minimally and precisely as possible)?**
- Create a storage class with storage type io1
- Create a persistent volume claim using the above storage class and try to modify the storage

**Anything else we need to know?**:
Possible root cause of the issue is the missing IOPS parameter in the ResizeDisk method: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/6d6e8b76f656789e6356e98ce4f9002c1b333e5c/pkg/cloud/cloud.go#L865
However it is specified in CreateDisk method: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/6d6e8b76f656789e6356e98ce4f9002c1b333e5c/pkg/cloud/cloud.go#L300
**Environment**
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:18:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-31566f", GitCommit:"31566f851673e809d4d667b7235ed87587d37722", GitTreeState:"clean", BuildDate:"2020-10-20T23:25:14Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by jahantech** [comment] 2020-11-26 13:28
Workaround was to modify the volume storage and iops via console/api and patch the PV with the correct value. This issue is related to kubernetes.io/aws-ebs provisioner. Closing this issue.

**Comment by sebradloff** [comment] 2020-11-30 17:57
I believe it is still relevant. I've resized my io1 PVCs several time without issues earlier this month. This morning is the first time I've had any issue.
kubernetes event log from the namespace of the PVC.
```
2m48s       Warning   VolumeResizeFailed       persistentvolumeclaim/prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-1   error expanding volume "monitoring/prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-1" of plugin "kubernetes.io/aws-ebs": AWS modifyVolume failed for vol-08654ea74c7882bd1 with InvalidParameterCombination: The parameter iops must be specified for io1 volumes.
            status code: 400, request id: 6e1e7dda-8f44-495a-bc75-50a3bb457ef8
```

storage class for reference:
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: io1
parameters:
  fsType: ext4
  iopsPerGB: "10"
  type: io1
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

I'm manually resolving by modifying the volume in the aws console directly.

**Comment by ayberk** [comment] 2020-12-01 18:21
This seems to be a regression on EBS side. [Documentation] clearly states that current iops will be retained if iops is not specified: `Default: If no IOPS value is specified, the existing value is retained.`

[Documentation]: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVolume.html

**Comment by CAR6807** [comment] 2020-12-07 14:44
Any reason this issue was closed?
Currently also running into this issue, despite successfully resizing earlier this month after switching over to EBS-CSI-Driver.
Any workarounds?

**Comment by ayberk** [comment] 2020-12-07 17:02
@CAR6807 one possible workaround is modifying the volume via console/API directly. 

I am tracking this issue internally with the EBS team. I'll provide an update as soon as I have one.

**Comment by ayberk** [comment] 2020-12-14 21:18
Apologies for the delay here. EBS has the fix merged it's being deployed. It'll take a couple of weeks to deploy it to all regions. I'll update the ticket again when the deployment is done.

**Comment by CAR6807** [comment] 2020-12-14 21:21
@ayberk Thank you for following up
The work around did work for us, but good to know it was an issue on Amazon's side
Thanks again

**Comment by ayberk** [comment] 2021-01-15 18:50
This issue should be resolved now. Please let me know if you still encounter it.

/close

**Closed** 2021-01-15 18:50 UTC
Labels: kind/bug
