### ISSUE TITLE
PVC attaching takes much time

### ISSUE THREAD

**Issue by sergeymatsak87** [kubernetes-sigs/aws-ebs-csi-driver#1302] opened 2022-07-07 11:18 UTC
Duplicating case https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1279 as we observe the same issue when detaching/deleting and attaching PVC to a new node takes more than 6 min and it's followed by a timeout

**What happened?**

```
  Normal   Scheduled               7m21s                  default-scheduler        Successfully assigned dev-test/bigid-cache-0 to ip-13-118-32-127.ec2.internal
  Warning  FailedAttachVolume      7m21s                  attachdetach-controller  Multi-Attach error for volume "pvc-xxx" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedMount             3m2s (x2 over 5m18s)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[redis-data], unattached volumes=[health redis-data config redis-tmp-conf tmp kube-api-access-98lr9 start-scripts]: timed out waiting for the condition
  Normal   SuccessfulAttachVolume  80s                    attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-xxx"
  Normal   Pulling                 64s                    kubelet                  Pulling image "docker.io/bitnami/redis:6.2.7-debian-10-r32"
  Normal   Pulled                  62s                    kubelet                  Successfully pulled image "docker.io/bitnami/redis:6.2.7-debian-10-r32" in 2.812050986s
  Normal   Created                 62s                    kubelet                  Created container redis
  Normal   Started                 62s                    kubelet                  Started container redis
```

EBS CSI Controller logs
Failure to Delete EBS volume after Detach 
```
I0706 19:22:20.580181       1 request.go:665] Waited for 1.119392703s due to client-side throttling, not priority and fairness, request: PATCH:https://172.20.0.1:443/apis/storage.k8s.io/v1/volumeattachments/csi-49dcfd3771191a910bb4dc00a3862dbc4332449c708072c95e11f43ead631eb3/status
I0706 19:22:21.580381       1 request.go:665] Waited for 1.331653146s due to client-side throttling, not priority and fairness, request: PATCH:https://172.20.0.1:443/apis/storage.k8s.io/v1/volumeattachments/csi-1973672463aeb63fb239e6370c04bb7df8bb50290d8d9f2a0d3690d134f3521a/status
I0706 19:22:21.786329       1 csi_handler.go:286] Failed to save detach error to "csi-49dcfd3771191a910bb4dc00a3862dbc4332449c708072c95e11f43ead631eb3": volumeattachments.storage.k8s.io "csi-49dcfd3771191a910bb4dc00a3862dbc4332449c708072c95e11f43ead631eb3" not found
I0706 19:22:21.786354       1 csi_handler.go:231] Error processing "csi-49dcfd3771191a910bb4dc00a3862dbc4332449c708072c95e11f43ead631eb3": failed to detach: could not mark as detached: volumeattachments.storage.k8s.io "csi-49dcfd3771191a910bb4dc00a3862dbc4332449c708072c95e11f43ead631eb3" not found
I0706 19:22:21.877958       1 csi_handler.go:261] Attached "csi-d0cb7bac7a53511c451712aaa8bc8bac79adc2d3426d993d1f14a135d84fb5ab"
I0706 19:22:21.986228       1 csi_handler.go:286] Failed to save detach error to "csi-a5b254ba7d7a41c45a4d772d05dc55a002bff25d9f53c1ee9bd945d98126b59d": volumeattachments.storage.k8s.io "csi-a5b254ba7d7a41c45a4d772d05dc55a002bff25d9f53c1ee9bd945d98126b59d" not found
I0706 19:22:21.986254       1 csi_handler.go:231] Error processing "csi-a5b254ba7d7a41c45a4d772d05dc55a002bff25d9f53c1ee9bd945d98126b59d": failed to detach: could not mark as detached: volumeattachments.storage.k8s.io "csi-a5b254ba7d7a41c45a4d772d05dc55a002bff25d9f53c1ee9bd945d98126b59d" not found
```

**What you expected to happen?**
It should not take so much time for PVC detaching and attaching to new k8s node. Compare to default Kubernetes Storage driver (gp2) where I do not see this issue it take a lot of time

**How to reproduce it (as minimally and precisely as possible)?**
You just need to terminate EC2 instance (k8s node) directly which statefulset is running on

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.22
- Driver version: 1.6.2

**Comment by torredil** [comment] 2022-07-07 18:07
I believe this is expected behavior, if you terminate your EC2 instance ungracefully (i.e. without safely evicting all of your pods through `kubectl drain`) the pods that are part of a `StatefulSet` will be stuck terminating on the shutdown node and cannot move to a new running node since the kubelet is not available to delete the pods. If there are volumes used by the pods, the `VolumeAttachment` objects will not be deleted from the original node so the volumes used by these pods cannot be attached to a new running node. There is work being done upstream to address this, K8s `v1.24` introduces alpha support for [Non-Graceful Node Shutdown](https://kubernetes.io/blog/2022/05/20/kubernetes-1-24-non-graceful-node-shutdown-alpha/) which would reduce this time, for more information see the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2268-non-graceful-shutdown) and https://github.com/kubernetes/kubernetes/pull/108486.

The 6 minute wait time before timing out is due to the default configuration of Attach/Detach controller timers. More specifically, [ReconcilerMaxWaitForUnmountDuration](https://github.com/kubernetes/kubernetes/blob/3f579d8971fcce96d6b01b968a46c720f10940b8/pkg/controller/volume/attachdetach/attach_detach_controller.go#L94) which is the max amount of time the attach/detach controller waits for a volume to be safely unmounted from a node. After 6 minutes, the controller assumes the node is unresponsive and attempts to detach the volume.

**Comment by amitde69** [comment] 2022-07-25 13:00
is [ReconcilerMaxWaitForUnmountDuration](https://github.com/kubernetes/kubernetes/blob/3f579d8971fcce96d6b01b968a46c720f10940b8/pkg/controller/volume/attachdetach/attach_detach_controller.go#L94) configurable ? is it part of the control plane ?

**Comment by torredil** [comment] 2022-07-25 15:11
@amitde69 [ReconcilerMaxWaitForUnmountDuration](https://github.com/kubernetes/kubernetes/blob/3f579d8971fcce96d6b01b968a46c720f10940b8/pkg/controller/volume/attachdetach/attach_detach_controller.go#L94) is currently not configurable: https://github.com/kubernetes/kubernetes/issues/105341.
The previously mentioned [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2268-non-graceful-shutdown#:~:text=%5BProposed%20change%5D%20Once,to%20be%20deleted.) addresses this 6 minute wait time by issuing a force detach if the `out-of-service` taint is present on the node.

**Comment by taylorsmithgg** [comment] 2022-10-26 17:30
+1 this makes some apps unusable (e.g. strimzi kafka operator) because of the frequent timeouts.
The same works fine on the default Kubernetes Storage driver (gp2).

**Comment by carlosjgp** [comment] 2022-11-23 17:33
I'm still seeing this
/remove-lifecycle stale

**Comment by carlosjgp** [comment] 2022-11-24 09:43
I'm still seeing this
K8s AWS EKS `1.22.11`
EBS image `v1.13.0`
/remove-lifecycle stale

**Comment by maximethebault** [comment] 2022-12-02 23:14
Experiencing the same behavior, and this is very concerning as this is a clear regression compared to previous versions of EKS.

We could observe the issue with a pod scheduled with Karpenter.
Karpenter cordoned & drained the node on which the pod was running (during consolidation), and it took several minutes for the pod to get back to the running state. The pod event log looks exactly the same as in the original issue report.

I want to make it clear that the node was not terminated ungracefully.

**Comment by samuel-form3** [comment] 2023-02-03 21:54
We're experiencing this on EKS 1.24 + EBS 1.12.

We use node-termination-handler to handle the graceful draining of the nodes. We observed that the volume becomes **detached from the old node** through AWS console, but the attachdetach controller doesn't detach the volume on the kubernetes api. 

This seems to be an issue on attachdetach controller to be honest. I'll try to dig out what maybe happening.

**Comment by stdmje** [comment] 2023-02-04 13:46
Same here.
EKS 1.24
Karpenter 0.23.0
ebs-csi-driver 1.15.0

**Comment by maximethebault** [comment] 2023-02-25 16:18
/kind bug

@torredil @ConnorJC3 comments + thumbs up deduplicated, **there are now 12 people that found their way to this Github issue to report this exact same issue**. And I suspect this will grow in number with EKS 1.22 ending support in June 2023 and EBS CSI Driver becoming mandatory in EKS 1.23.

Can we please have an official word on this? Do you confirm the issue, or do you still think this is an expected, perfectly normal behavior? Do you maybe lack resource to look into this, should we alert our AWS account reps to get more attention on this?

**Comment by ConnorJC3** [comment] 2023-02-25 18:57
Hi all, I can't make any specific promises before I get a chance to look into it, but I will investigate this bug sometime during the next work week.

In the meantime, can anyone affected here please clarify that this issue is happening to them (only) when they terminate the EC2 instance behind a node without draining it first?

If you can reproduce this under other scenarios that are different, please provide information on how to do that, thanks!

**Comment by maximethebault** [comment] 2023-02-25 22:53
Thanks!

Running a "kubectl drain <node>" on a node running a stateful workload is enough to reproduce this issue. The node **doesn't have to be terminated ungracefully**.

**Comment by jhass** [comment] 2023-02-26 07:56
For me killing a pod of a stateful set with a PVC attached is enough already to reproduce.

**Comment by igor-nikiforov** [comment] 2023-02-28 01:04
I have this issue every time when we starting process of nodes replacement. Killing a pods with StatefulSet usually not enough so we a I also kill pods with EBS CSI Controller and then issue disappears.

**Comment by maximethebault** [comment] 2023-03-12 09:16
> Hi all, I can't make any specific promises before I get a chance to look into it, but I will investigate this bug sometime during the next work week.
> 
> In the meantime, can anyone affected here please clarify that this issue is happening to them (only) when they terminate the EC2 instance behind a node without draining it first?
> 
> If you can reproduce this under other scenarios that are different, please provide information on how to do that, thanks!

Hi @ConnorJC3 

Anything else you need, you let us know!

**Comment by ConnorJC3** [comment] 2023-03-13 18:40
Hi all, sorry about the somewhat late response. I have been trying to reproduce this locally via methods such as `kubectl drain`, but I cannot seem to do so.

If anyone experiencing this issue _not related to an ungraceful shutdown_ (ungraceful shutdowns causing this is expected behavior and out of our control) could provide one of the two, that would be very helpful:

1. A minimum set of manifests to reproduce the issue with some level of consistency OR
2. Logs from the EBS CSI Controller `ebs-plugin` and `csi-attacher` containers with the log level for both turned up to 4 when the issue occurs

**Comment by danielloader** [comment] 2023-04-12 13:07
Not got reproduction steps per se, but running stateful sets with pv/pvcs on karpenter on spot instances with a node lifespan TTL of 15mins is a nice way to force the issue to happen quickly, as nodes are constantly churning and re-attaching to the PVs takes a while.

**Comment by tkatrichenko** [comment] 2023-04-13 07:37
Using Spot instances on AWS and when an instance is terminated the same issue occurs

EKS: 1.22
ebs-csi-driver: v1.17
node-termination-handler: v1.19

**Comment by maximethebault** [comment] 2023-04-15 15:01
I don't know what changed exactly, but I cannot reproduce the issue after upgrading to the driver's latest version.

Reverting to an older version like 1.12.1 and the issue is back.

I will upgrade all production clusters to the latest version and keep you updated if the issue is back.
Meanwhile, would be nice if anyone else can confirm the issue is gone after upgrading to the driver latest version.

**Comment by maherbeg** [comment] 2023-04-25 21:24
@maximethebault After upgrading your production clusters, are you still seeing the issue?

**Comment by igor-nikiforov** [comment] 2023-05-09 15:42
I could confirm that this issue is still exist with EKS 1.25 / 1.26 and latest EBS driver version 1.18.0.

**Comment by VitaliiBabii** [comment] 2023-05-15 15:34
Hi all, 
I also faced with PVC(EBS) attach timeouts. Sometimes PVC attachment takes up to 1 hour. 
In csi-attacher container logs I see lots of "client-side throttling". Is there the way to increase request's quota on csi-attacher side ?

```
I0515 15:12:23.707456       1 request.go:682] Waited for 3.792550031s due to client-side throttling, not priority and fairness, request: PATCH:https://100.64.0.1:443/api/v1/persistentvolumes/pvc-485c1d77-30e1-4006-bad4-396eeee17a6b
I0515 15:12:24.907002       1 request.go:682] Waited for 3.766319675s due to client-side throttling, not priority and fairness, request: PATCH:https://100.64.0.1:443/api/v1/persistentvolumes/pvc-cef2f6e7-df16-4d1d-ad50-7981093c78ad
I0515 15:12:25.907372       1 request.go:682] Waited for 3.392822052s due to client-side throttling, not priority and fairness, request: PATCH:https://100.64.0.1:443/api/v1/persistentvolumes/pvc-20aa26b3-f495-456e-a284-d9327bf73a84
I0515 15:12:27.107446       1 request.go:682] Waited for 3.192762704s due to client-side throttling, not priority and fairness, request: PATCH:https://100.64.0.1:443/api/v1/persistentvolumes/pvc-591f7379-5c9f-45f1-a42d-ef53808d0684
```

**Comment by VitaliiBabii** [comment] 2023-05-18 19:01
PVC attaching delay fixed by increasing attacher and provisioner qps and burst .
--kube-api-burst=20
--kube-api-qps=10.0

**Comment by BrianKopp** [comment] 2023-05-24 03:22
> If anyone experiencing this issue _not related to an ungraceful shutdown_ (ungraceful shutdowns causing this is expected behavior and out of our control) could provide one of the two, that would be very helpful:

Am I understanding this correctly that a stateful workload using a PVC would be rendered irrecoverable due to an ungraceful node shutdown?

**Comment by BrianKopp** [comment] 2023-05-24 17:24
Is this related? https://github.com/kubernetes-csi/external-attacher/issues/215

**Comment by ichbestimmtnicht** [comment] 2023-07-14 11:17
I can confirm the issue of long re-atachments for the addon v1.19.0-eksbuild.2 from kubernetes version 1.23 upwards and found kind of an easier workaround as I was impatiently updating a cluster: I deleted the `volume.kubernetes.io/selected-node: [ip...]` annotation from all pvc's prior to updating and the switch to the new nodes was almost smooth.
I tested this for k8s versions 1.24 -> 1.25 -> 1.26. The 1.23 -> 1.24 update was my test update where i discovered this fix while the pods couldn't be rescheduled.

This bug is a real pain and in my opinion this should be a dealbreaker for everyone who tests eks thoroughly.

**Comment by wallhided** [comment] 2023-08-14 13:53
I had same issue with gp2 volume in 1.24, 1.25, 1.26. Pod restart process took from 3 to 20 minutes, even if node hadn't changed. I had opened case and  Support engineer from AWS suggested to add 
`fsGroupChangePolicy: "OnRootMismatch"` to securityContext of StatefulSet.
More info -> https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/

This option helped me and pod started to run without significant delays in following options:
- Without changing node
- Previous node terminated gracefully and new node requested by controller(Karpenter)

**Comment by shay-ul** [comment] 2023-09-13 15:14
For whoever is still impacted by this behaviour - make sure to update to the latest ebs csi version.

**Comment by TJCNI** [comment] 2023-09-23 15:27
Problem still exists on EKS v1.27.4-eks-cedffd4, Karpenter v0.30.0, aws-ebs-csi-driver v1.23.0

**Comment by hobbsh** [comment] 2023-10-05 02:23
We have Karpenter termination handling setup and still experience this in EKS 1.27, ebs-csi-driver 1.23, Karpenter 0.30.0. Based on logs (and probably to no one's surprise) the driver is failing to detatch the volume. I also see is that the node in question becomes `NotReady` (but not cordoned/drained) making me think that something is up with the kubelet, but Karpenter does not seem to notice or care.

```
E1005 01:55:03.601580       1 driver.go:122] "GRPC error" err="rpc error: code = Internal desc = Could not detach volume \"vol-0691fe2d3686d6859\" from node \"i-07c1e6216907ac9a9\": context canceled"
```

**Comment by ConnorJC3** [comment] 2023-10-05 14:16
@hobbsh EBS detaches rely on the EC2 instance's cooperation (if it is still online) - the OS must "give up" the volume, traditionally done on *nix OSes by `umount`ing it.

Thus, if your node breaks in such a way that the volume isn't detached on the node side (for example, because the Kubelet is broken and never asks the EBS CSI Driver to unmount the volume) - but the node is still running, the EBS CSI Driver will get stuck indefinitely trying to detach.

This is intentional design, as taking the volume away from a running node without it's cooperation (what EBS calls a "force detach") can cause data loss. The EBS CSI Driver will never perform a force detach on your behalf because of the risks associated.

The feature that @torredil mentions above is only applicable when nodes are gracefully terminated (i.e. drained before shutdown). If your nodes are not being gracefully terminated, you'll need to work with Karpenter to figure out why that is occurring.

**Comment by doryer** [comment] 2023-10-31 11:17
Anyone on K8S and CSI versions managed to solve it and can share?

**Comment by blowfishpro** [comment] 2023-11-03 00:16
> The EBS CSI Driver will never perform a force detach on your behalf because of the risks associated.

So how are unrecoverable instance failures supposed to be handled?  Things like hardware failures are individually rare, but across a large fleet of nodes become a common enough occurrence.  In these cases the volumes are never going to be gracefully unmounted, and we're left to either wait many minutes for some timeouts to be hit on the AWS side and the instance to stop, or to manually force-detach the volumes.  Either way some data loss is inevitable, but requiring a human to intervene and force-detach the volumes is generally not what we want to be doing.  And waiting for the timeouts to be hit usually means more downtime than we want (for the services we have not yet managed to make HA).

**Comment by torredil** [comment] 2024-01-18 17:58
@blowfishpro

> So how are unrecoverable instance failures supposed to be handled?

As a first step, ensure that [Graceful Node Shutdown](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/) is enabled in your cluster by configuring `ShutdownGracePeriod` and `ShutdownGracePeriodCriticalPods`. The default values are set to zero, so you will need to configure them as appropriate.

Doing the above will allow the driver's [preStop hook](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/889b1e4016054b6690c1e71a2c9df0f9892988da/cmd/hooks/prestop.go#L18) to execute even during unexpected shutdowns, and thus prevent the node pod from terminating for a period of 30 seconds, given there are `VolumeAttachment` objects associated with the relevant instance. **If volumes are successfully unmounted in that 30 second window, they will not be "locked up" for 6 minutes.**

That said, in rare corner cases where Kubelet's Node Shutdown Manager is unable to detect shutdown events and delay it by the `ShutdownGracePeriod`, you can manually add an out-of-service taint on the Node to reconcile the state before 6 minute timer lapses, see [Non-Graceful Node Shutdown](https://kubernetes.io/blog/2023/08/16/kubernetes-1-28-non-graceful-node-shutdown-ga/):

```
kubectl taint nodes <node-name> node.kubernetes.io/out-of-service=nodeshutdown:NoExecute
```

> Either way some data loss is inevitable, but requiring a human to intervene and force-detach the volumes is generally not what we want to be doing

A different perspective on this: data loss / corruption of any kind is unacceptable. Delayed attachments are certainly highly undesirable and indicative of room for improvements, but potentially compromising a user's data is never the right tradeoff. Relevant to this discussion, Sig-Storage is currently working on a feature that allows for disabling the 6 minute force detach timer in A/D controller (doing so would be the equivalent of replacing 6 minutes with "infinity", requiring operator intervention by instructing Kubernetes that the node has really been shut-down): https://github.com/kubernetes/kubernetes/issues/120328

----

To the best of my knowledge, the issue of delayed attachments as a result of graceful termination workflows has been addressed. If anyone runs into issues using the latest version of the driver, please report it and be sure to include all relevant context / information that may be helpful in tracking down the root cause so that we can address that promptly for you. Thank you!

/close

**Closed by torredil** 2024-01-18 17:58 UTC
Labels: kind/bug

**Comment by jainpratik163** [comment] 2025-03-12 06:38
we are also facing same issue in EKS 1.30 means we are moving from 1.29 to 1.30.
is the any fix ?

**Comment by ElijahQuinones** [comment] 2025-03-12 19:18
Hi @jainpratik163,

This issue is closed we do not typically monitor closed issues. If you are still experiencing this issue please follow the steps @torredil provided above and open a new issue with the relavent information so we can take a look at it. Thank you !
