### ISSUE TITLE
Max node volume count does not take network interface into account

### ISSUE THREAD

**Issue by AntonioDiTuri** [kubernetes-sigs/aws-ebs-csi-driver#1728] opened 2023-08-28 15:27 UTC
/kind bug

**What happened?**

On eks-prod cluster I had 27 volumes on a node and I tried to schedule a single pod with a single volume on that node.
I expected that node to welcome the new pod but this was not the case.
I thought the aws-ebs-csi driver was not telling the scheduler about the volume limitations and I went on dev to to some tests.

I went to read this documentation and I suspected there was a problem with the count related to the network interface.
[The doc](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html) reports the following: 

> Most of these instances support a maximum of 28 attachments. For example, if you have no additional network interface attachments on an m5.xlarge instance, you can attach up to 27 EBS volumes (28 volume limit - 1 network interface).

On dev I created a managed node group with a single node.
By default 1 volume is created to let the ec2 instance boot.
I then created a statefulset with 27 replicas each mounting one node.
My objective was to try to see if the 28th pod was actually able to mount its volume or not.

The following happened:
- 1 volume for the node
- 26 pods scheduled correctly
- 1 pod left in the init 0/1 state reason being _"AttachVolume.Attach failed for volume "pvc-yyy": rpc error: code = Internal desc = Could not attach volume "vol-xxx" to node "zzz": attachment of disk "vol-xxx" failed, expected device to be attached but was attaching"_

Then I tried to scale up to 28 replicas (total number of wanted volumes now 29) and the last pod created was left in the pending state as expected with the following message:

`
"Node unavailable, max exceeded max volume count"
`

**What you expected to happen?**

I would expect to see the same message I used to see before on the 27th pod in the statefulset: 
`
"Node unavailable, max exceeded max volume count"
`

The driver thinks that there are only 27 volumes (1 boot + 26 from the statefuleset) available but one slot is taken for network interface therefore the 27th pods is pending in the attaching state while it should be stopped by the scheduler the same way the 28th is.

**How to reproduce it (as minimally and precisely as possible)?**

EKS cluster with k8s version 1.24, create a node group with a single m6i.2xlarge instance.

Volume limit for this instance is 28, 1 slot is occupied by the network interface, 1 is the boot volume so we have 26 slots left.

Spin up any statefulset with 1 volume per pod and set the number of replicas to 27.

26 pods are correctly created, one cannot leave the init 0/1 state reason being:

```
AttachVolume.Attach failed for volume "pvc-yyy": rpc error: code = Internal desc = Could not attach volume "vol-xxx" to node "zzz": attachment of disk "vol-xxx" failed, expected device to be attached but was attaching
```

If we now try to scale up to 28 pods the 28th pod it is unscheduled with the correct message

**Anything else we need to know?**:
I have taken a look to the source code and I think it would be enough to update the constants in [this file](https://github.com/ConnorJC3/aws-ebs-csi-driver/blob/ba53ad39e66df05fd291f5dba63f4a4da09f55b9/pkg/cloud/volume_limits.go) but I don't know it this leads to other problems

**Environment**
- Kubernetes version (use `kubectl version`): 1.24
- Driver version: I used the chart version 1.20.0 which is using the 1.20.0 driver version

**Comment by ConnorJC3** [comment] 2023-09-27 14:56
Hi @AntonioDiTuri

When I test locally, I see that the driver correctly reports to Kubernetes that an `m6i.2xlarge` instance has a limit of 26 volumes (see `Count: 26` in the output).

```
$ kubectl describe csinodes.storage.k8s.io i-007d2b76f09bf38a2
Name:               i-007d2b76f09bf38a2
Labels:             <none>
...
Spec:
  Drivers:
    ebs.csi.aws.com:
      Node ID:  i-007d2b76f09bf38a2
      Allocatables:
        Count:        26
      Topology Keys:  [topology.ebs.csi.aws.com/zone]
Events:               <none>
```

I tested this on both the latest supported driver version (`v1.23.0`) and the version you are using (`v1.20.0`), and got the same result.

If possible, can you provide more specific reproduction steps to cause this behavior? Thanks!

Also be aware that if the driver is reporting the correct limit on your cluster, you may be running into this Kubernetes bug: https://github.com/kubernetes/kubernetes/issues/95911

**Comment by AndrewSirenko** [comment] 2023-11-22 16:23
Going to close this for now due to @ConnorJC3's comment. Thank you.

/close

**Closed by AndrewSirenko** 2023-11-22 16:23 UTC
Labels: kind/bug

**Comment by AntonioDiTuri** [comment] 2023-12-04 15:01
I am sorry for taking long to reply. Thanks for providing an answer I tried to run the same command as you. Unfortunately I don't see 26 but 27: 

```
k describe csinodes.storage.k8s.io node.xxx
Name:               node.xxx
Labels:             <none>
Annotations:        storage.alpha.kubernetes.io/migrated-plugins:
                      kubernetes.io/aws-ebs,kubernetes.io/azure-disk,kubernetes.io/azure-file,kubernetes.io/cinder,kubernetes.io/gce-pd,kubernetes.io/vsphere-vo...
CreationTimestamp:  Fri, 01 Dec 2023 11:44:28 +0100
Spec:
  Drivers:
    ebs.csi.aws.com:
      Node ID:  node.xxx
      Allocatables:
        Count:        27
      Topology Keys:  [topology.ebs.csi.aws.com/zone]
Events:               <none>
```

Why that can be?
Moreover when reading the aws doc this should be the case: 

> Most of these instances support a maximum of 28 attachments. For example, if you have no additional network interface attachments on an m5.xlarge instance, you can attach up to 27 EBS volumes (28 volume limit - 1 network interface). 

m6i.2xlarge is not listed between the exeptions
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html

**Comment by AntonioDiTuri** [comment] 2023-12-04 15:03
Can you please re-open the issue?

**Comment by AntonioDiTuri** [comment] 2023-12-05 07:52
Thanks for debugging it! It was very helpful for me cause I realized that we had an old value with a configuration that was overriding the  `Allocatables:Count:` with value 27. Now it is solved. Thanks again a lot for the support!
