### ISSUE TITLE
EBS Controller pod crashing

### ISSUE THREAD

**Issue by shinji62** [kubernetes-sigs/aws-ebs-csi-driver#1300] opened 2022-07-07 01:49 UTC
/kind bug

**What happened?**
Controller is crashing and panicking,  not sure this is the cause, but our volume are not being able to be reattach again.

```
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner I0707 01:37:01.000700       1 controller.go:1471] delete "pvc-077d190c-0836-44b1-bac7-96f12d6208ac": started
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner E0707 01:37:01.000783       1 controller.go:1481] delete "pvc-077d190c-0836-44b1-bac7-96f12d6208ac": volume deletion failed: persistentvolume pvc-077d190c-0836-44b1-bac7-96f12d6208ac is still attached to node ip-10-19-171-223.ap-northeast-1.compute.internal
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner W0707 01:37:01.000829       1 controller.go:989] Retrying syncing volume "pvc-077d190c-0836-44b1-bac7-96f12d6208ac", failure 0
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner E0707 01:37:01.000865       1 controller.go:1007] error syncing volume "pvc-077d190c-0836-44b1-bac7-96f12d6208ac": persistentvolume pvc-077d190c-0836-44b1-bac7-96f12d6208ac is still attached to node ip-10-19-171-223.ap-northeast-1.compute.internal
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner I0707 01:37:01.000964       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-077d190c-0836-44b1-bac7-96f12d6208ac", UID:"0a63204b-45fb-49a4-964a-2d1674d47a7c", APIVersion:"v1", ResourceVersion:"7017724", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' persistentvolume pvc-077d190c-0836-44b1-bac7-96f12d6208ac is still attached to node ip-10-19-171-223.ap-northeast-1.compute.internal
ebs-csi-controller-7f7d8649dd-bq2gp ebs-plugin I0707 01:37:01.007605       1 cloud.go:610] Waiting for volume "vol-04bbbf52bcccff707" state: actual=attaching, desired=attached
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner I0707 01:37:01.009162       1 controller.go:1471] delete "pvc-077d190c-0836-44b1-bac7-96f12d6208ac": started
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner E0707 01:37:01.009381       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner goroutine 225 [running]:
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1780320, 0x2976450})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x7d
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0009a1250})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner panic({0x1780320, 0x2976450})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/go/pkg/csiprow.XXXXcGaFcn/go-1.17.3/src/runtime/panic.go:1038 +0x215
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner github.com/kubernetes-csi/external-provisioner/pkg/controller.(*csiProvisioner).Delete(0xc0000d2780, {0x1c09090, 0xc0005a4e40}, 0xc0009c0500)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/pkg/controller/controller.go:1177 +0x4e2
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).deleteVolumeOperation(0xc0002b6f00, {0x1c09090, 0xc0005a4e40}, 0xc0009c0500)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1473 +0x175
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).syncVolume(0xc0006b8cd0, {0x1c09090, 0xc0005a4e40}, {0x1998940, 0xc0009c0500})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1109 +0xe7
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).syncVolumeHandler(0xc0002b6f00, {0x1c09090, 0xc0005a4e40}, {0xc0009991a0, 0x40edaf})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1045 +0x69
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).processNextVolumeWorkItem.func1(0xc0002b6f00, 0xc0004f2c60, {0x16bd780, 0xc0009a1250})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:987 +0x1b0
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).processNextVolumeWorkItem(0xc0002b6f00, {0x1c09090, 0xc0005a4e40})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1004 +0x59
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).runVolumeWorker(...)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:905
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1.3()
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:857 +0x45
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fe81674b318)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x1bd8120, 0xc0004f2c60}, 0x1, 0xc00005b6e0)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner created by sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:857 +0xa78
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner panic: runtime error: invalid memory address or nil pointer dereference [recovered]
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	panic: runtime error: invalid memory address or nil pointer dereference
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x159a602]
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner goroutine 225 [running]:
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0009a1250})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0xd8
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner panic({0x1780320, 0x2976450})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/go/pkg/csiprow.XXXXcGaFcn/go-1.17.3/src/runtime/panic.go:1038 +0x215
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner github.com/kubernetes-csi/external-provisioner/pkg/controller.(*csiProvisioner).Delete(0xc0000d2780, {0x1c09090, 0xc0005a4e40}, 0xc0009c0500)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/pkg/controller/controller.go:1177 +0x4e2
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).deleteVolumeOperation(0xc0002b6f00, {0x1c09090, 0xc0005a4e40}, 0xc0009c0500)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1473 +0x175
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).syncVolume(0xc0006b8cd0, {0x1c09090, 0xc0005a4e40}, {0x1998940, 0xc0009c0500})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1109 +0xe7
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).syncVolumeHandler(0xc0002b6f00, {0x1c09090, 0xc0005a4e40}, {0xc0009991a0, 0x40edaf})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1045 +0x69
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).processNextVolumeWorkItem.func1(0xc0002b6f00, 0xc0004f2c60, {0x16bd780, 0xc0009a1250})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:987 +0x1b0
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).processNextVolumeWorkItem(0xc0002b6f00, {0x1c09090, 0xc0005a4e40})
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1004 +0x59
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).runVolumeWorker(...)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:905
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1.3()
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:857 +0x45
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fe81674b318)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x1bd8120, 0xc0004f2c60}, 0x1, 0xc00005b6e0)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner created by sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1
ebs-csi-controller-7f7d8649dd-bq2gp csi-provisioner 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:857 +0xa78
ebs-csi-controller-7f7d8649dd-bq2gp ebs-plugin I0707 01:37:01.281673       1 cloud.go:610] Waiting for volume "vol-08efe320b98e55cb4" state: actual=attaching, desired=attached
```

**What you expected to happen?**
Not to crash
**How to reproduce it (as minimally and precisely as possible)?**
Just a lot of bound / unbound from Kubernetes

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): v1.21.12-eks-a64ea69
- Driver version:
-
```yaml
app.kubernetes.io/version=1.8.0                                                                                                                                                              
helm.sh/chart=aws-ebs-csi-driver-2.8.0
```

**Comment by torredil** [comment] 2022-07-11 17:18
Can you provide more details or context to help reproduce this? Is the controller crashing during startup? 
Taking a look at the `ebs-plugin` container logs could be helpful: 
- `kubectl logs -n kube-system $(kubectl get lease -n kube-system ebs-csi-aws-com -o=jsonpath="{.spec.holderIdentity}") -c ebs-plugin`

**Comment by shinji62** [comment] 2022-07-12 02:26
Ok I will get the logs as well.

**Comment by shinji62** [comment] 2022-07-12 05:42
here the current logs [log-for-aws.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/9089826/log-for-aws.txt)

**Comment by torredil** [comment] 2022-07-14 00:32
Thanks for providing the logs and further clarification. This issue appears to be a duplicate of #1301, do you mind if we close this and continue the conversation there? If you feel that this issue is not a duplicate, please feel free to `/reopen` it. Thanks again for reporting this.

**Closed by torredil** 2022-07-14 00:32 UTC
Labels: kind/bug
