### ISSUE TITLE
Csi-attacher Looses Connection to Driver Unix Socket

### ISSUE THREAD

**Issue by dmitrii-didenko** [kubernetes-sigs/aws-ebs-csi-driver#1875] opened 2023-12-15 13:16 UTC
/kind bug

**What happened?**
We are observing the issue where csi-attacher sidecar container exits frequently with the following message:
```
1 connection.go:142] Lost connection to unix:///var/lib/csi/sockets/pluginproxy/csi.sock.
1 connection.go:97] Lost connection to CSI driver, exiting
```
According to this change https://github.com/kubernetes-csi/external-attacher/pull/123 I assume that ebs-plugin container indeed closes socket somehow which causes csi-attacher to be restarted. However, we see no suspicious logs from ebs-plugin at the event time:
```
csi_handler.go:282] Detaching "csi-115cdec4b0fe42eb07f43b0af068d2b71c0e203992aa182fed625bea1ec0742e"
cloud.go:862] "Waiting for volume state" volumeID="vol-0290170d55c6d53b8" actual="detaching" desired="detached" |  
1 cloud.go:862] "Waiting for volume state" volumeID="vol-0290170d55c6d53b8" actual="detaching" desired="detached" |  
1 controller.go:465] "ControllerUnpublishVolume: detaching" volumeID="vol-0290170d55c6d53b8" nodeID="i-041ccc637fb15b3ec"
```

**What you expected to happen?**
csi-attacher should not exit and keep connected via socket

**How to reproduce it (as minimally and precisely as possible)?**
Unfortunately, we do not have exact steps to reproduce this. 

**Anything else we need to know?**:
We noticed one thing - this happens only on clusters with frequent resizing events (by cluster autoscaler or spot instances changes).
<img width="1500" alt="Screenshot 2023-12-15 at 15 07 00" src="https://github.com/kubernetes-sigs/aws-ebs-csi-driver/assets/81171763/54b72958-79af-424b-b3f7-eb35a2a64068">

Do we have any options we can enable to collect more information on this?

**Environment**
- Kubernetes version v1.28.4-eks-8cb36c9
- Driver version: v1.25.0
- Bottlerocket nodes: v1.16.1

**Comment by AndrewSirenko** [comment] 2023-12-15 15:12
Hi @dmitrii-didenko, I was able to isolate this bug the [v4.4.2 of the csi-attacher](https://github.com/kubernetes-csi/external-attacher/blob/release-4.4/CHANGELOG/CHANGELOG-4.4.md#changelog-since-v441) (as well as the latest csi-provisioner and csi-resizer versions). I will post my logs shortly. 

I have tried:
- v1.25 of driver with latest sidecar images -> Restart bug
- v1.25 of driver with previous patch version of sidecar images  (v4.4.1 of csi-attacher) -> No restart bug
- v1.23 of driver with latest sidecar images -> Restart bug
- v1.23 of driver with older version of sidecar images bundled with it (v4.4.0 of csi-attacher) -> No restart bug

Reproduction steps:
1. Deploy any version of the aws-ebs-csi-driver with the latest version of the csi-attacher, csi-provisioner, or csi-resizer sidecar images. 
2. Wait ~45 minutes
3. Dynamically provision or resize a volume
4. Note that the csi-attacher, csi-provisioner, csi-resizer container will restart due to lost connection to driver socket

**Comment by AndrewSirenko** [comment] 2023-12-15 15:16
The latest patch version of csi-attacher, csi-provisioner, and csi-resizer only had dependency upgrades. This suggests that one of those upgrades might have caused this regression. 

<img width="805" alt="image" src="https://github.com/kubernetes-sigs/aws-ebs-csi-driver/assets/68304519/e904e4a5-428b-47f1-a917-9144e474f342">

We are almost finished releasing v1.26.0 of aws-ebs-csi-driver for helm, which includes dependency upgrades. I will look for this restart bug there to see if it still occurring before filing an issue on the external-attacher project. 

Thank you for raising this issue @dmitrii-didenko!

**Comment by AndrewSirenko** [comment] 2023-12-15 16:02
Started adding logs here [AndrewSirenko/csi-sidecar-container-restart-issue-logs: A collection of logs to help debug [Csi-attacher Looses Connection to Driver Unix Socket · Issue #1875 · kubernetes-sigs/aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1875)](https://github.com/AndrewSirenko/csi-sidecar-container-restart-issue-logs)

You will find that if we use csi-attacher <= 4.4.1, that the csi-attacher will no longer restart, but that the csi-provisioner sidecar will still restart. 

Let me know if there is a more helpful way to present the information. I am trying to reproduce on driver v1.26.0 now.

**Comment by dmitrii-didenko** [comment] 2023-12-15 16:31
Thank you very mush for update! So if I got you right the only workaround is to configure the following?
- v1.23 of driver with older version of sidecar images bundled with it (v4.4.0 of csi-attacher)

**Comment by AndrewSirenko** [comment] 2023-12-15 17:40
@dmitrii-didenko the workarounds are to either:
- Use aws-ebs-csi-driver v1.24.0 and lower (Which don't include the latest versions of the sidecar images)
- Use newer versions of the aws-ebs-csi-driver, but explicitly [replace the version tag for each sidecar](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/277d76fb5ca67a574a0e9ddfa4e44dfa0ea5be44/charts/aws-ebs-csi-driver/values.yaml#L22) in values.yaml to versions other than csi-attacher ([v4.4.2](https://github.com/kubernetes-csi/external-attacher/releases/tag/v4.4.2)), csi-provisioner ([v3.6.2](https://github.com/kubernetes-csi/external-provisioner/releases/tag/v3.6.2)), csi-resizer ([v1.9.2](https://github.com/kubernetes-csi/external-resizer/releases/tag/v1.9.2)).

**Comment by AndrewSirenko** [comment] 2023-12-28 02:59
Sig-storage has released new versions of the sidecars. We will include them in our next patch release.

**Comment by faganihajizada** [comment] 2024-01-03 13:24
> Sig-storage has released new versions of the sidecars. We will include them in our next patch release.

@AndrewSirenko Thanks! Do you have an ETA for the next patch release?

**Comment by AndrewSirenko** [comment] 2024-01-03 16:40
Hi @faganihajizada, we're waiting on [EKS Distro](https://github.com/aws/eks-distro) to release the patched versions of the sidecars during their bi-weekly release. Their ETA is today. We will start the release process as soon as those sidecar images are released. 

ETA for the helm patch release is most likely tomorrow (jan 4). We will also start the EKS add-on release process today, but our team is not in control about when that will be released (typically a few business days after the helm release).

**Comment by AndrewSirenko** [comment] 2024-01-06 00:12
The new EKS-D csi sidecar images were released 24 minutes ago. We are starting our Helm release now.

**Comment by AndrewSirenko** [comment] 2024-01-06 20:09
Helm release is out [on our release-1.26 branch](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/release-1.26). 

Add-on release will likely* come out sometime on the later half of next week. @faganihajizada

**Comment by faganihajizada** [comment] 2024-01-08 13:16
> Helm release is out [on our release-1.26 branch](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/release-1.26).
> 
> Add-on release will likely* come out sometime on the later half of next week. @faganihajizada

Thank you @AndrewSirenko 🤝 

An engineer in the team tried it, and we got:

```chart "aws-ebs-csi-driver" version "2.26.1" not found in https://kubernetes-sigs.github.io/aws-ebs-csi-driver```

**Comment by AndrewSirenko** [comment] 2024-01-08 19:01
Done @faganihajizada , we were waiting on the team to confirm there wouldn't be merge conflicts

/close

**Comment by AndrewSirenko** [comment] 2024-01-08 19:01
Thank you everybody!

**Closed by AndrewSirenko** 2024-01-08 19:01 UTC
Labels: kind/bug

**Comment by AndrewSirenko** [comment] 2024-01-10 23:15
One last update: the v1.26.1 add-on is released in all regions. Thank you!

```
> aws eks describe-addon-versions --addon-name aws-ebs-csi-driver --region us-east-1
{
    "addons": [
        {
            "addonName": "aws-ebs-csi-driver",
            "type": "storage",
            "addonVersions": [
                {
                    "addonVersion": "v1.26.1-eksbuild.1",
...
```
