### ISSUE TITLE
VolumeSnapShot Ready to Use False

### ISSUE THREAD

**Issue by mlopez-eb** [kubernetes-sigs/aws-ebs-csi-driver#871] opened 2021-05-05 06:05 UTC
/kind bug

**What happened?**

I'm on Kubernetes version 1.19 through AWS EKS (highest available).
I deployed CSI driver with alpha features and attempted to follow instructions for [Volume Snapshot](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot). I meticulously followed every step for driver install and snapshot, but upon creating the snapshot, the `Ready to Use: false'. When I describe the snapshot, I get the following warning and it hangs waiting:

```kubectl describe volumesnapshot.snapshot.storage.k8s.io ebs-volume-snapshot                                      01:20:15
Name:         ebs-volume-snapshot
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2021-05-05T05:19:34Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  Generation:  1
  Managed Fields:
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:source:
          .:
          f:persistentVolumeClaimName:
        f:volumeSnapshotClassName:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-05-05T05:19:34Z
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
    Manager:      snapshot-controller
    Operation:    Update
    Time:         2021-05-05T05:19:34Z
    API Version:  snapshot.storage.k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:boundVolumeSnapshotContentName:
        f:readyToUse:
    Manager:         snapshot-controller
    Operation:       Update
    Time:            2021-05-05T05:19:34Z
  Resource Version:  85400838
  Self Link:         /apis/snapshot.storage.k8s.io/v1/namespaces/default/volumesnapshots/ebs-volume-snapshot
  UID:               3656d855-1f2b-4e0d-91dc-fef45452407a
Spec:
  Source:
    Persistent Volume Claim Name:  ebs-claim
  Volume Snapshot Class Name:      csi-aws-vsc
Status:
  Bound Volume Snapshot Content Name:  snapcontent-3656d855-1f2b-4e0d-91dc-fef45452407a
  Ready To Use:                        false
Events:
  Type     Reason                  Age                  From                 Message
  ----     ------                  ----                 ----                 -------
  Warning  SnapshotFinalizerError  110s (x2 over 110s)  snapshot-controller  Failed to check and update snapshot: snapshot controller failed to update default/ebs-volume-snapshot on API server: Operation cannot be fulfilled on volumesnapshots.snapshot.storage.k8s.io "ebs-volume-snapshot": the object has been modified; please apply your changes to the latest version and try again
  Normal   CreatingSnapshot        110s                 snapshot-controller  Waiting for a snapshot default/ebs-volume-snapshot to be created by the CSI driver.
  Normal   CreatingSnapshot        110s                 snapshot-controller  Waiting for a snapshot default/ebs-volume-snapshot to be created by the CSI driver.
```
One of the 2 snapshot-controller logs continues repeating the following:

```
I0505 05:34:49.829952       1 leaderelection.go:346] lock is held by snapshot-controller-9f68fdd9-mgcbd and has not yet expired
I0505 05:34:49.829968       1 leaderelection.go:248] failed to acquire lease kube-system/snapshot-controller-leader
I0505 05:34:56.520690       1 leaderelection.go:346] lock is held by snapshot-controller-9f68fdd9-mgcbd and has not yet expired
I0505 05:34:56.520708       1 leaderelection.go:248] failed to acquire lease kube-system/snapshot-controller-leader
```

But there is an ebs-snapshot-controller pod as well displaying strange items in the logs
```
pods | grep contr                                                                                                01:37:05
default                ebs-snapshot-controller-0                                      1/1     Running   0          104m
kube-system            ebs-csi-controller-b78db65b9-kglcx                             6/6     Running   0          104m
kube-system            ebs-csi-controller-b78db65b9-pqnb8                             6/6     Running   0          104m
kube-system            snapshot-controller-9f68fdd9-gg2vg                             1/1     Running   0          80m
kube-system            snapshot-controller-9f68fdd9-mgcbd                             1/1     Running   0          80m
```

**What you expected to happen?**

I expect the example to work in creating a successful snapshot before attempting this on actual PVCs.

**How to reproduce it (as minimally and precisely as possible)?**

1. Use the alpha version of EBS csi driver by `kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/alpha/?ref=master"`.
2. Following the [Volume Snapshot](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot) example.
3. You'll see the `Ready to Use` status as `false` and the snapshot creation hangs.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:58:13Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`
- Driver version: `latest`

**Comment by shihtiy-tw** [comment] 2021-05-05 14:41
Hi @mlopez-eb,

I was able to reproduce the same issue and I saw that you are using the EBS CSI driver of alpha version in your use case. Would you check the clusterrolebinding for "ebs-csi-snapshotter-binding" by

```sh
$ kubectl get clusterrolebindings.rbac.authorization.k8s.io ebs-csi-snapshotter-binding -o yaml
```

And check if the subject are like following:

```yaml
# for ebs-csi-snapshotter-binding
subjects:
- kind: ServiceAccount
  name: ebs-csi-controller-sa
  namespace: default
```

If yes, it may be related to the issue I reported in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/870. It is due to the namespace misconfig issue in clusterrolebinding.

You can try the following commands to check the service account "ebs-csi-controller-sa" should be in kube-system namespace. If yes, you can try to change the namespace to "kube-system" in the clusterrolebinding for "ebs-csi-snapshotter-binding":

```sh
$ kubectl -n kube-system get sa | grep "ebs-csi-controller-sa"

$ kubectl edit clusterrolebindings.rbac.authorization.k8s.io ebs-csi-snapshotter-binding
subjects:
- kind: ServiceAccount
  name: ebs-csi-controller-sa
  namespace: kube-system # <---------------
```

Then you can follow the [volume snapshot example](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot) to see if you can create the snapshot successfully.

If you install the EBS csi driver via helm in https://github.com/kubernetes-sigs/aws-ebs-csi-driver#installation. It should work.

**Comment by AndyXiangLi** [comment] 2021-05-10 23:52
Same issue with #872 and #870, fixed in this [PR](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/879)
/close

**Closed by AndyXiangLi** 2021-05-10 23:52 UTC
Labels: kind/bug
