### ISSUE TITLE
Version of image at k8s.gcr.io do run correct version

### ISSUE THREAD

**Issue by pserranoa** [kubernetes-sigs/aws-ebs-csi-driver#1423] opened 2022-10-12 18:33 UTC
/kind bug

**What happened?**
There is a different version of driver running the following container images.

k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.12.0 => Contains v1.11.4 driver version
public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.12.0 => Contains v1.12.0 driver version

**k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.12.0** container image
`docker run -ti k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.12.0 -version
{
  "driverVersion": "v1.11.4",
  "gitCommit": "",
  "buildDate": "2022-10-04T16:18:13+00:00",
  "goVersion": "go1.19.1",
  "compiler": "gc",
  "platform": "linux/amd64"
}
`

**k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.12.0** container image
`
docker run -ti public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.12.0 -version
{
  "driverVersion": "v1.12.0",
  "gitCommit": "eebda781d5f100c5d01a919721fb2f2152e22b72",
  "buildDate": "2022-10-04T15:37:22+00:00",
  "goVersion": "go1.19.1",
  "compiler": "gc",
  "platform": "linux/amd64"
}
`

**What you expected to happen?**
The driver over each container images should be the same

**How to reproduce it (as minimally and precisely as possible)?**
Run each container to get version

- Driver version: v1.12.0

**Comment by ConnorJC3** [comment] 2022-10-12 18:50
This is purely a visual bug. I can confirm that `k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.12.0` is actually 1.12.0, just incorrectly labeled as v1.11.4 due to a bug in our build system. We're currently in the process of releasing 1.12.1 and 1.11.5 to address some CVEs in the base image, but future versions on GCR will be fixed to correctly report the driver version.

**Comment by pserranoa** [comment] 2022-10-12 19:19
thanks for your fast answer!

**Closed** 2022-10-12 20:53 UTC
Labels: kind/bug
