### ISSUE TITLE
My volume snapshot is always not ready to use and data not recovered after restoring from the snapshot

### ISSUE THREAD

**Issue by dhouhamaa** [kubernetes-sigs/aws-ebs-csi-driver#506] opened 2020-05-15 08:12 UTC
I'am working with an EKS cluster from AWS , version 1.15
I installed : 
- the ebs csi driver following the official guide documentation from aws ( link :  https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html )
- installed the Snapshot Beta CRDs and the Snapshot Controller ( link : https://github.com/kubernetes-csi/external-snapshotter )
and i was following this scenario https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot .
Th problem is that my volume snapshot has always the state ReadyToUse : False ,  and I restored another PVC from the snapshot but it was missing all the data that I previously had , in addition to that , I cannot find the snapshot created inside the AWS snapshots console ! 
Am I missing some configuration ? or maybe problem with versions am using ?

**Comment by nitinkansal1984** [comment] 2020-05-15 23:45
@dhouhamaa  you should check your IAM policies and Role attached to worker node.

**Comment by leakingtapan** [comment] 2020-05-19 04:07
Is this a duplicate of #426 @dhouhamaa ?

**Comment by dhouhamaa** [comment] 2020-05-19 07:43
Yes probably , will close this issue then

**Closed** 2020-05-19 07:44 UTC
